version: "3.4"

services:
    usher-ws:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: usher-ws
        restart: always
        ports:
            - 8000:80

    ui:
        build:
            context: ./docs/
            dockerfile: ./Dockerfile
        container_name: ui
        restart: always
        ports:
            - 8008:80